-- Initial migration: example users table.
-- Generated by drizzle-kit from drizzle/neon/schema.ts.
-- Run via: pnpm db:migrate (reads NEON_DATABASE_URL from .dev.vars or env).

CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" text NOT NULL,
	"name" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
